version: '3'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_clothline
        ports:
            - "8887:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        #      - mysql
        networks:
            - laravel

    mysql:
        image: mysql/mysql-server:8.0
        container_name: mysql_clothline
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
            # - "3305:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_USERNAME}'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_clothline
        volumes:
            - .:/var/www/html
        ports:
            - "9007:9000"
        networks:
            - laravel

    redis:
        image: redis
        container_name: redis_clothline
        ports:
            - '6377:6379'
        restart: always
        networks:
            - laravel

    # SMTP Server
    smtp:
        platform: linux/x86_64
        image: mailhog/mailhog
        container_name: mailhog_clothline
        logging:
            driver: 'none'
        ports:
            - '8027:8025'
        restart: always
        networks:
            - laravel
